
export const BAR_TOUCH_START = "<BAR-TOUCH-START-EVENT>";
export const BAR_TOUCH_END = "<BAR-TOUCH-END-EVENT>";
export const BAR_LONG_PRESS = "<BAR-LONG-PRESS-EVENT>";
export const BAR_SINGLE_TAP = "<BAR-SINGLE-TAP-EVENT>";
